@startuml main
scale 4000*3000
package MainBundle {
        class AppState {

        }
        class HookManager {

        }
        AppState "1" *-- "n" HookManager : contains
    AppState "1" *-- "n" Plugin : tracks state for
    
    class Plugin {

    }
    class Hook <<Types>> {

    }
    
    class Loader {

    }
    
    class BTFFile {

    }
    
    class Util {

    }
}
HookManager "1" -- "1" Hook : contains

    package BasePlugin {

        class BasePlugin {
        }
        mix_component App
        mix_component JSONDisplay
        mix_component BTFMetadataDisplay
        mix_component BTFMetadataConciseDisplay
        mix_component RenderHooks
        mix_component SafeGLIInspector
        mix_component Tooltip

  }

    package BaseThemePlugin {
        class BaseThemePlugin {
        }
        mix_node "style<U+002E>css"
    }

    package BlueThemePlugin {
        class BlueThemePlugin {
        }
    }

    BlueThemePlugin -> BaseThemePlugin

     package BookmarksPlugin {
        class BookmarksPlugin {
        }
        mix_component BookmarkUI
    }

    package ConverterPlugin {
        class ConverterPlugin {
        }
        class BPMWriter {
        }
        class ConverterStrategy {
        }
        class ConverterStrategyConfig {
        }
        class ConverterUI {
        }
        class PNGWriter {
        }
        class Writer {
        }
        mix_component ConverterView
        PNGWriter -> Writer
        BPMWriter -> Writer
    }

    package ImpExpPlugin {
        class ImpExpPlugin {
        }
    }

    package LightControlPlugin {
        class LightControlPlugin {
        }
        class Hemisphere {
        }
        mix_node "hemisphere<U+002E>glsl"
        mix_component LightControlUI
        mix_component HemisphereDisplay
        mix_component ShowSliders
        mix_component DomeFactor
    }

    package NotesPlugin {
        class NotesPlugin {
        }
        mix_component NotesUI
        mix_component NotesOverlay
        mix_component NotesPopers
        mix_component NotesInnerDisplay

    }

     package PaintPlugin {
        class PaintPlugin {
        }
        mix_node "init<U+002E>glsl"
        mix_node "mixer<U+002E>glsl"
        mix_node "paint<U+002E>glsl"
        mix_database PaintNode
        mix_component PaintUI
    }

    package PTMConverterPlugin {
        class PTMConverterPlugin {
        }
    }

    package PTMRendererPlugin {
        class PTMRendererPlugin {
        }
        mix_database PTMRGB
        mix_database PTMLRGB
        mix_node "ptmrgb<U+002E>glsl"
        mix_node "ptmlrgb<U+002E>glsl"
        mix_node "ptmlrgb_normals<U+002E>glsl"
    }

    package QuickPanPlugin {
        class QuickPanPlugin {
        }
        mix_component QuickPanUI
        mix_component Grabber

        mix_node "quickpan<U+002E>glsl"
        mix_node "grabber<U+002E>glsl"
    }

    package RedThemePlugin {
        class RedThemePlugin {
        }
    }

    RedThemePlugin -> BaseThemePlugin

    package RendererPlugin {
        class RendererPlugin {
        }
        mix_component RendererView
        mix_component RenderModePicker
        mix_component Upload
        mix_component Stack
        mix_node "noise<U+002E>glsl"
    }

    package RotationPlugin {
        class RotationPlugin {
        }
        mix_node "rotation<U+002E>glsl"
        mix_node "centerer<U+002E>glsl"
        mix_component RotationUI
        mix_component CentererUI
        mix_component RotationSlider
        mix_component SettingsKeepCenter
        mix_database Rotator
        mix_database Centerer
    }

    package SettingsPlugin {
        class SettingsPlugin {
        }
        mix_component SettingsUI
    }

    package SingleViewPlugin {
        class SingleViewPlugin {
        }
        mix_component SingleView
    }

    package TabViewPlugin {
        class TabViewPlugin {
        }
        mix_component TabView
    }

    package ZoomPlugin {
        class ZoomPlugin {
        }
        mix_component ZoomUI
        mix_database ZoomNode
    }


Loader -> AppState : creates initial
Loader -> App : mounts
App -> AppState : renders

Plugin "1" *-- "n" Hook : declares

mix_node "index"
"index" -> Loader

 ConverterPlugin -[hidden]up- index
 ImpExpPlugin -[hidden]up- BookmarksPlugin
 SettingsPlugin -[hidden]up- BookmarksPlugin
 TabViewPlugin -[hidden]up- SingleViewPlugin
BasePlugin -[hidden]up- ConverterPlugin

hide <<SFC>> circle
hide <<Config>> circle
hide <<Types>> circle

@enduml