@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v1.0.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome/server.puml
!includeurl ICONURL/font-awesome/book.puml

!include ./components.plantuml

left to right direction
skinparam packageStyle rectangle
skinparam componentStyle uml2


rectangle "Current Students" {
actor  Johannes <<"MSc Computer Science">>
actor Taylor <<"Phd Archaeology">>
}

rectangle "PBR CompSci" {
actor Stefano
actor Jassim
}

rectangle "Graphics CompSci"  as graphics {

}

rectangle "OSAD" as osad {

}

rectangle "Downstream Users" as users {
actor "Computer Science Student"
actor "Archaeologist"
actor "Artefact Enthusiast"
}

FA_BOOK(mscthesis, "MSc Thesis")
note right of mscthesis : To be finished September 2018

mscthesis -> webviewer


FA_BOOK(phdthesis, "Phd Thesis")

Johannes -> mscthesis
Stefano -> mscthesis
Jassim -> mscthesis

Taylor -> phdthesis
 osad -> phdthesis




@enduml
